### ISSUE TITLE
npmjs.com release for additional SPDX code added needed

### ISSUE THREAD

**Issue by Martii** [jslicense/spdx-osi.json#2]
https://www.npmjs.com/package/spdx-osi doesn't seem to include 8b69d8f962d5012f696dfd9de58894f51b27b08f thus blocking https://www.npmjs.com/package/spdx-is-osi and indirectly https://www.npmjs.com/package/spdx-license-ids in our implementation.

Will we expect an update soon please?

Thanks for a moment of your time.

**Comment by Martii** [comment]
\*Gentle reminder bump\*

**Comment by kemitchell** [comment]
2.0.0 coming soon.

I've added you as a collaborator this repo. Please send PRs for significant changes.

**Comment by Martii** [comment]
Thanks. Now that 2.0.0 of this is on npmjs.com, should the package that has this dependency be updated too at the line of [/jslicense/spdx-is-osi.js/blob/`35add02`/package.json#L7](https://github.com/jslicense/spdx-is-osi.js/blob/35add0245db20936028844ff04e215e83d233206/package.json#L7) along with a version bump over there? e.g. do you want a PR over there after some brief manual testing?

**Comment by kemitchell** [comment]
@Martii, by all means, do what you can.

**Comment by Martii** [comment]
Done... closing.
